name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Node v18
      uses: actions/setup-node@v2
      with:
         node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_BRANCH: deploy
        BUILD_SCRIPT: npm run build
        BUILD_DIR: guide/.vuepress/dist
        CNAME: https://www.xxx.com  
